config/routes.rb
Rails.application.routes.draw do
  

  get '/cart', to: "carts#show"
  resources :products 
  post "/products/:id/save", to: "products#save", as:"product_save"
  post "/products/:id/unsave", to: "products#unsave", as:"product_unsave"
  
  get "/products/:id/setAvailableColours", to: "products#setAvailableColours"
  get "/products/:id/setAvailableQuantity", to: "products#setAvailableQuantity"

  
  get "sign_up", to: "user_registration#new"
  post "sign_up", to: "user_registration#create"
  
  get "login", to: "user_login#new"
  post "login", to: "user_login#create"
  delete "logout", to: "user_login#destroy"
  
  get "/auth/twitter/callback", to: "user_login#omniauth"
  
  get "/newins", to: "products#allNewIns"
  get "/men", to: "products#allMen"
  get "/women", to: "products#allWomen"
  get "/kids", to: "products#allKids"
  
  post "products/:id", to: "products#editList" 
  
  post "cart_items", to: "cart_items#create"

  post "cart_items/:id/add", to: "cart_items#add", as: "cart_item_add"
  post "cart_items/:id/reduce", to: "cart_items#reduce", as: "cart_item_reduce"
  delete "cart_items/:id", to: "cart_items#destroy", as: "cart_item_remove"
  
  get "/support", to: "application#showSupport"
  get "/savedItems", to: "products#allSavedItems"
  get "/account", to: "application#account"
  
  get "/newsletter/subscribe"
  
  post "/cart/checkout", to: "carts#checkOut", as: "checkout"
  
  root to: "main#index"
  
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :products, through: :cart_items
    
    def sub_total
        sum = 0
        self.cart_items.each do |cart_item|
          sum+= cart_item.total_price
        end
        return sum
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    
    def total_price
        self.quantity * self.product.price
    end
    

end

app/models/colour.rb
class Colour < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    def self.filterByMen
        Item.where(category: "Men")
    end

    def self.filterByWomen
        Item.where(category: "Women")
    end

    def self.filterByKids
        Item.where(category: "Kids")
    end

    # def self.filterByNewins
    #     Item.where(category: "Newins")
    # end

    def self.CountRowsMen
        Item.where(category: "Men").size
    end

    def self.CountRowsWomen
        Item.where(category: "Women").size
    end

    def self.CountRowsKids
        Item.where(category: "Kids").size
    end

    def self.CountRowsNewins
        Item.where(category: "Newins").size
    end

    def self.GetTotalItems
        Item.count
    end

    def self.GetPoplularItems
        # Item.where("popularity > ?", 2)
        Item.find_by_sql ["SELECT * FROM items WHERE popularity > 3 ORDER BY popularity DESC"]
    end

    def self.RecentlyStocked
        Item.where(date_stocked: 3.months.ago..Time.now.end_of_month).all
    end

    def self.GetRandom
        Item.find_by_sql ["SELECT * FROM items ORDER BY RANDOM() LIMIT 1"]
    end

    def self.SavedTable
        r= Item.find_by_sql ["SELECT * FROM saveds"]
        puts r
    end

    def getItemById
        Item.where(id: params[:id])
    end
end

app/models/newuser.rb
class Newuser < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    
    def total_price
        self.quantity * self.product.price
    end
end

app/models/product.rb
class Product < ApplicationRecord
   
   def increasePopularity
       self.popularity += 1
       self.save
   end
   
   def decreasePopularity
       if self.popularity > 1
           self.popularity -= 1
           self.save       
       end
   end
end

app/models/product_item.rb
class ProductItem < ApplicationRecord
  belongs_to :item
  belongs_to :saved
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
    belongs_to :product
end

app/models/saved.rb
class Saved < ApplicationRecord
  belongs_to :item
  belongs_to :user

#   has_many :product_items, dependent: :destroy
	
# 	def add_product(product_id)
# 		current_item = product_items.find_by(product_id: product_id)
# 		if current_item
# 			current_item.quantity += 1
# 		else
# 		  current_item = product_items.build(product_id: product_id)
# 		end
# 		current_item
# 	end
	
# 	def total_price
# 		product_items.to_a.sum{|item| item.total_price}
# 	end

	def self.GetTotalSavedItems
		Saved.count
	end
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}, if: :isNotTwitterAccount
    validates :password, format: { with: /[a-zA-Z0-9]{8,20}/, message:"must be 8-20 characters long"}, if: :isNotTwitterAccount



    def isNotTwitterAccount
        provider != "twitter"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/newusers_helper.rb
module NewusersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/saveds_helper.rb
module SavedsHelper
end

app/views/shared/_collections_card.html.erb
<br><h2>Collections</h2>

<%= link_to "/newins" do %>
<h4 class="img-thumbnail" style="
    height: 55px;
    text-align: center;
">New ins</h4>
<% end %>
<br>

<%= link_to "/men" do %>
<h4 class="img-thumbnail" style="
    height: 55px;
    text-align: center;
">Men</h4>
<% end %>
<br>

<%= link_to "/women" do %>
<h4 class="img-thumbnail" style="
    height: 55px;
    text-align: center;
">Women</h4>
<% end %>
<br>

<%= link_to "/kids" do %>
<h4 class="img-thumbnail" style="
    height: 55px;
    text-align: center;
">Kids</h4>
<% end %>
<br>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light shadow">

    <%= link_to "Home", root_path, class: "navbar-brand text-success logo h1 align-self-center" %>

    <div class="container d-flex justify-content-between align-items-center">

        <%# <a class="navbar-brand text-success logo h1 align-self-center" href="/">
            Zay
        </a> %>

        <%# <button id="hamburgerMenuIcon" class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
        data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button> %>

        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
        data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="menu-container" onclick="myFunction(this)">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
            </div>
        </button>

        <script>
            function myFunction(x) {
                x.classList.toggle("change");
            }
        </script>

        <button class="fa fa-shopping-bag px-3" aria-hidden="true" style="
            margin-left: 275px;
            margin-right: -17px;
            background: none;
            border: white;
        "></button>

        <button class="fa fa-fw fa-search" style="
            margin-right: 18px;
            background: none;
            border: white;
        "></button>

        <div id="templatemo_main_nav" class="align-self-center collapse navbar-collapse flex-fill d-lg-flex justify-content-lg-between">
            <div class="flex-fill">
                <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                    <h4>Shop</h4>
                    <li class="nav-item">
                        <%= link_to "Men", home_men_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Women", home_women_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Kids", home_kids_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "New-ins", home_newins_path, class:"nav-link" %>
                    </li>
                    <hr>
                    <li class="nav-item">
                        <%= link_to "Saved", home_saved_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Help & Support", home_help_path, class:"nav-link" %>
                    </li>
                </ul>
            </div>
            <%# <div class="navbar align-self-center d-flex">
                <a class="nav-icon d-none d-lg-inline" href="#" data-bs-toggle="modal" data-bs-target="#templatemo_search">
                    <i class="fa fa-fw fa-search text-dark mr-2"></i>
                </a>
                <a class="nav-icon position-relative text-decoration-none" href="#">
                    <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
                    <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">7</span>
                </a>
                <a class="nav-icon position-relative text-decoration-none" href="#">
                    <i class="fa fa-fw fa-user text-dark mr-3"></i>
                    <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">+99</span>
                </a>
            </div> %>
        </div>

        

        <%# <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
            <div class="input-group">
                <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
                <div class="input-group-text">
                    
                </div>
            </div>
        </div> %>

    </div>
</nav>

app/views/shared/_product_card.html.erb
<%= link_to product do %>
<%= image_tag(product.imageString, class: "img-fluid") %>
<h3><%= product.title %></h3>
<h3>$<%= product.price %></h3>
<% end %>

app/views/shared/_products_grid.html.erb
<% @products.in_groups_of(4, false).each do |group| %>
    <div class='row'>
      <% group.each do |product| %>
      <div class='col-3 col-6'>
      <%= render partial: "shared/product_card", locals: {product: product} %>
        </a>
        <div><%= number_to_currency(product.price) %></div> 
        </div>
      <% end %>
    </div>
  <% end %>

app/views/shared/_save_product.html.erb
<% if cookies[:savedList] and cookies[:savedList].split(" ").include? (product.id.to_s) %>
      <%= button_to "Unsave", product_unsave_path(id: product.id), method: :post %>

<% else %>
  <%= button_to "Save",product_save_path(id: product.id), method: :post %>
<% end %>

app/views/shared/save_button.js.erb
$('#div_id').html("<%= render :partial => 'shared/save_product' %>");