config/routes.rb
Rails.application.routes.draw do
  

  get '/cart', to: "carts#show"
  resources :products 
  post "/products/:id/save", to: "products#save", as:"product_save"
  post "/products/:id/unsave", to: "products#unsave", as:"product_unsave"
  
  get "/products/:id/setAvailableColours", to: "products#setAvailableColours"
  get "/products/:id/setAvailableQuantity", to: "products#setAvailableQuantity"

  
  get "sign_up", to: "user_registration#new"
  post "sign_up", to: "user_registration#create"
  
  get "login", to: "user_login#new"
  post "login", to: "user_login#create"
  delete "logout", to: "user_login#destroy"
  
  get "/auth/twitter/callback", to: "user_login#omniauth"
  
  get "/newins", to: "products#allNewIns"
  get "/men", to: "products#allMen"
  get "/women", to: "products#allWomen"
  get "/kids", to: "products#allKids"
  
  post "products/:id", to: "products#editList" 
  
  post "cart_items", to: "cart_items#create"

  post "cart_items/:id/add", to: "cart_items#add", as: "cart_item_add"
  post "cart_items/:id/reduce", to: "cart_items#reduce", as: "cart_item_reduce"
  delete "cart_items/:id", to: "cart_items#destroy", as: "cart_item_remove"
  
  get "/support", to: "application#showSupport"
  get "/savedItems", to: "products#allSavedItems"
  get "/account", to: "application#account"
  
  get "/newsletter/subscribe"
  
  post "/cart/checkout", to: "carts#checkOut", as: "checkout"
  
  root to: "main#index"
  
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :products, through: :cart_items
    
    def sub_total
        sum = 0
        self.cart_items.each do |cart_item|
          sum+= cart_item.total_price
        end
        return sum
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    
    def total_price
        self.quantity * self.product.price
    end
    

end

app/models/colour.rb
class Colour < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    def self.filterByMen
        Item.where(category: "Men")
    end

    def self.filterByWomen
        Item.where(category: "Women")
    end

    def self.filterByKids
        Item.where(category: "Kids")
    end

    # def self.filterByNewins
    #     Item.where(category: "Newins")
    # end

    def self.CountRowsMen
        Item.where(category: "Men").size
    end

    def self.CountRowsWomen
        Item.where(category: "Women").size
    end

    def self.CountRowsKids
        Item.where(category: "Kids").size
    end

    def self.CountRowsNewins
        Item.where(category: "Newins").size
    end

    def self.GetTotalItems
        Item.count
    end

    def self.GetPoplularItems
        # Item.where("popularity > ?", 2)
        Item.find_by_sql ["SELECT * FROM items WHERE popularity > 3 ORDER BY popularity DESC"]
    end

    def self.RecentlyStocked
        Item.where(date_stocked: 3.months.ago..Time.now.end_of_month).all
    end

    def self.GetRandom
        Item.find_by_sql ["SELECT * FROM items ORDER BY RANDOM() LIMIT 1"]
    end

    def self.SavedTable
        r= Item.find_by_sql ["SELECT * FROM saveds"]
        puts r
    end

    def getItemById
        Item.where(id: params[:id])
    end
end

app/models/newuser.rb
class Newuser < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    
    def total_price
        self.quantity * self.product.price
    end
end

app/models/product.rb
class Product < ApplicationRecord
   
   def increasePopularity
       self.popularity += 1
       self.save
   end
   
   def decreasePopularity
       if self.popularity > 1
           self.popularity -= 1
           self.save       
       end
   end
end

app/models/product_item.rb
class ProductItem < ApplicationRecord
  belongs_to :item
  belongs_to :saved
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
    belongs_to :product
end

app/models/saved.rb
class Saved < ApplicationRecord
  belongs_to :item
  belongs_to :user

#   has_many :product_items, dependent: :destroy
	
# 	def add_product(product_id)
# 		current_item = product_items.find_by(product_id: product_id)
# 		if current_item
# 			current_item.quantity += 1
# 		else
# 		  current_item = product_items.build(product_id: product_id)
# 		end
# 		current_item
# 	end
	
# 	def total_price
# 		product_items.to_a.sum{|item| item.total_price}
# 	end

	def self.GetTotalSavedItems
		Saved.count
	end
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}, if: :isNotTwitterAccount
    validates :password, format: { with: /[a-zA-Z0-9]{8,20}/, message:"must be 8-20 characters long"}, if: :isNotTwitterAccount



    def isNotTwitterAccount
        provider != "twitter"
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
      set_cart
  end
  
  def checkOut
    set_cart
    @cart.cart_items.each do |cart_item|
      cart_item.destroy
    end
    redirect_to "/cart"
  end
  
  def set_cart
    @cart = Cart.find_by(user_id: session[:current_user])
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/newusers_helper.rb
module NewusersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/saveds_helper.rb
module SavedsHelper
end

app/views/carts/show.html.erb
<div class="row" style="width: 100%">
  <div class="col-md-10 mt-md-0 mt-3 mx-auto">
    <h2>Your shopping cart</h2>
    
    <% if @cart.cart_items.empty? %>
    <br>
   <div class="text-center"> <p>Go Get Shopping ! :) </p></div
    <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">Product</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col">Total</th>
        </tr>
      </thead>
      <tbody>
        <% @cart.cart_items.each do |cart_item| %>
          <tr>
            <td><%= image_tag(cart_item.product.imageString, width: '50%') %></td>
            <td><%= cart_item.product.title %></td>
            <td><%= number_to_currency(cart_item.product.price) %></td>
            <td><%= cart_item.quantity %></td>
            <td><%= link_to "Add one", cart_item_add_path(:id => cart_item), method: :post %></td>
            <td><%= link_to "Reduce one", cart_item_reduce_path(:id => cart_item), method: :post %></td>
            <td><%= link_to "Remove item", cart_item_remove_path(cart_item), method: :delete %></td>
            <td><%= number_to_currency(cart_item.total_price) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <h4>Cart Total: $<%= @cart.sub_total %></h4>
  </div>
</div>

<div>
  <%= button_to "Check Out",checkout_path, method: :post, class: "btn btn-block bg-dark text-light" %>
</div>

<% end %>