config/routes.rb
Rails.application.routes.draw do
  

  get '/cart', to: "carts#show"
  resources :products 
  post "/products/:id/save", to: "products#save", as:"product_save"
  post "/products/:id/unsave", to: "products#unsave", as:"product_unsave"
  
  get "/products/:id/setAvailableColours", to: "products#setAvailableColours"
  get "/products/:id/setAvailableQuantity", to: "products#setAvailableQuantity"

  
  get "sign_up", to: "user_registration#new"
  post "sign_up", to: "user_registration#create"
  
  get "login", to: "user_login#new"
  post "login", to: "user_login#create"
  delete "logout", to: "user_login#destroy"
  
  get "/auth/twitter/callback", to: "user_login#omniauth"
  
  get "/newins", to: "products#allNewIns"
  get "/men", to: "products#allMen"
  get "/women", to: "products#allWomen"
  get "/kids", to: "products#allKids"
  
  post "products/:id", to: "products#editList" 
  
  post "cart_items", to: "cart_items#create"

  post "cart_items/:id/add", to: "cart_items#add", as: "cart_item_add"
  post "cart_items/:id/reduce", to: "cart_items#reduce", as: "cart_item_reduce"
  delete "cart_items/:id", to: "cart_items#destroy", as: "cart_item_remove"
  
  get "/support", to: "application#showSupport"
  get "/savedItems", to: "products#allSavedItems"
  get "/account", to: "application#account"
  
  get "/newsletter/subscribe"
  
  post "/cart/checkout", to: "carts#checkOut", as: "checkout"
  
  root to: "main#index"
  
end

app/models/product.rb
class Product < ApplicationRecord
   
   def increasePopularity
       self.popularity += 1
       self.save
   end
   
   def decreasePopularity
       if self.popularity > 1
           self.popularity -= 1
           self.save       
       end
   end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy]
  
  
  
  # GET /products or /products.json
  def index
    @category = "Products"
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    @availableSizes = ProductVariant.where(product_id: @product.id).distinct("size").pluck("size")
    @availableColours = ProductVariant.where(product_id: @product.id, size: @availableSizes[0]).distinct("colour").pluck("colour")
    @availableQuantity =  ProductVariant.where(product_id: @product.id, size: @availableSizes[0], colour: @availableColours[0]).pluck("quantity")
  end
  
  def setAvailableColours
  
    set_product
    @availableColours =  ProductVariant.where(product_id: @product.id, size: params[:size]).distinct("colour").pluck("colour")
    respond_to do |format|
      format.html
      format.json {render json: @availableColours}
    end
  end
  
  def setAvailableQuantity
    set_product
    @availableQuantity =  ProductVariant.where(product_id: @product.id, size: params[:size], colour: params[:colour]).pluck("quantity")
    respond_to do |format|
      format.html
      format.json {render json: @availableQuantity}
    end
  end
  
  
  def save
    if (cookies[:savedList])
        cookies[:savedList] += " " + params[:id]
        product = Product.find(params[:id])
        product.increasePopularity
    else
        cookies[:savedList] = params[:id]
    end
      redirect_back(fallback_location: root_path)
  end
  
  def unsave

      list = cookies[:savedList].split(" ")
      list.delete(params[:id])
      cookies[:savedList] = list.join(" ")
      product = Product.find(params[:id])
        product.decreasePopularity
    set_product
    redirect_back(fallback_location: root_path)
    
  
  end

  # GET /products/new
  def new
    @product = Product.new
  end
  
  def addToCart
    Cart
  end
  
  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  

  
  


    
  
  
  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def allWomen
    @category = "Women"
    @products = Product.where(category: "women")
    render "products/index"
  end
  
  def allMen
    @category = "Men"

    @products = Product.where(category: "men")
    render "products/index"
  end
  
  def allKids
    @category = "Kids"

    @products = Product.where(category: "kids")
    render "products/index"
  end
  
  def allNewIns
    @category = "New Ins"

    @products = Product.where(created_at: 3.months.ago..Time.now.end_of_month)
    render "products/index"
  end
  
  def allSavedItems
    @category = "Saved Items"
    @products = Product.where(id: cookies[:savedList].split(" ").map(&:to_i))
  render "products/index"
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:company, :title, :size, :price, :imageString, :action)
    end
    
    
    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :imageString %>
    <%= form.text_field :imageString %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

    <h2><%= @category %></h2>
    
    
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Filters
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= form_with local:true, url: login_path do |form| %>
  
 
  
  <div class="mb-3">
    <%= form.label :size %>
    <%= select_tag :size, options_for_select(["s","m","l","xl","xxl"]), multiple: true %>
  </div>

  <div class="mb-3">
    <%= form.label :color %>
    <%= select_tag :color, options_for_select(["red","blue","black","brown","green"]) %>
  </div>

  <div class="mb-3">
    <%= form.submit "Filter", class: "btn btn-primary" %>
  </div>
<% end %>
  </div>
  <br>
</div>
    <%= render partial: "shared/products_grid" %>
  </tbody>
</table>

<br>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag(@product.imageString, class: "img-fluid") %>
    </div>
    <div class="carousel-item">
      <%= image_tag(@product.imageString, class: "img-fluid") %>
    </div>
    <div class="carousel-item">
      <%= image_tag(@product.imageString, class: "img-fluid") %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<p>
  <strong>Company:</strong>
  <%= @product.company %>
</p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<div id="div_id">
 <%= render partial: "shared/save_product", locals: {product: @product} %>
 </div>

<%= form_with local:true, url: cart_items_path(:product_id => @product.id) do |form| %>

  <div class="mb-3">
    <%= form.label :size %>
    <%= select_tag :size, options_for_select(@availableSizes ), id: "size-list"%>
  </div>

  <div class="mb-3">
    <%= form.label :colour %>
    <%= select_tag :colour, options_for_select(@availableColours), id: "colour-list" %>
  </div>
  <h3><%= @availableColors%></h3>
  <div class="mb-3">
    <%= form.label :quantity %>
    <%= select_tag :quantity, options_for_select((1..@availableQuantity[0]).to_a), id: "quantity-list" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Add To Cart", class: "btn btn-primary" %>
  </div>
  
  <%end%>
  
<script>
  $("#size-list").change(function(){
    var url = window.location.pathname + "/setAvailableColours"+ ""
  $.ajax({
    url: url,
    dataType: 'json',
    data: {size: $(this).val()},
    type: 'GET',
    success: function(data){ 
     $("#colour-list").children().remove();
      // Create options and append to the list
      var listitems = []; 
      $.each(data,function(key, value) { 
        
        listitems += '<option value="' + value+ '">' + value + '</option>';    }); 
    $("#colour-list").append(listitems);
    
     },
     complete: function(){setQuantity()}
  });
  
});


  $("#colour-list").change(setQuantity);
  
 function setQuantity(){
    var url = window.location.pathname + "/setAvailableQuantity"+ ""
  $.ajax({
    url: url,
    dataType: 'json',
    data: {size: $("#size-list").val(), colour: $("#colour-list").val() },
    type: 'GET',
    success: function(data){ 
     $("#quantity-list").children().remove();
      // Create options and append to the list
      var listitems = []; 
      for(var i = 1; i <= data[0]; i++){ 
        
        listitems += '<option value="' + i+ '">' + i + '</option>';    }
    $("#quantity-list").append(listitems);
     }
  });
}

</script>